.TH tuxedo-tsw 1 "2021-06-07" "tuxedo-tsw-1.0"

.SH NAME
tuxedo-tsw - TUXEDO Touchpad Switcher

.SH SYNOPSIS
.SY tuxedo-tsw
.OP on\fR|\fBoff
.YS

.SH DESCRIPTION
.I tuxedo-tsw
is a small utility to enable/disable the touchpad on TUXEDO Computers laptops.
.RE
(SEE \fBSUPPORTED DEVICES\fR)

.SH OPTIONS
.B on
.RE
.RS 5
Enable the touchpad.
.RE
.B off
.RE
.RS 5
Disable the touchpad.



.SH SUPPORTED DEVICES
- TUXEDO Polaris 17 (AMD)
